blank_issues_enabled: false
contact_links:
  - name: RPCE Community Support
    url: https://github.com/extend-chrome/rollup-plugin-chrome-extension/discussions/new
    about: Need help? Start a community discussion! ğŸ§‘â€ğŸ’»ğŸ§‘ğŸ½â€ğŸ’»
