name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Runs linter and unit tests in src folder
  lint:
    name: Run Lint

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.1.0
        with:
          # Version of PNPM to install
          version: 6.3.0
          # Where to store PNPM files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          # run_install: true

      - name: Check CWD
        run: node -e "console.log('cwd', process.cwd())"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm lint

  # Runs integration tests for MV3
  e2e:
    name: E2E Playwright Tests

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.1.0
        with:
          # Version of PNPM to install
          version: 6.3.0
          # Where to store PNPM files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          # run_install: true

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm i

      - name: Run E2E vite build tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test:ci:e2e:build

      - name: Run E2E vite serve tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test:ci:e2e:serve

      - name: Check for image diffs
        id: diff
        run: echo "::set-output name=files::$(find . -wholename '__image_snapshot_diffs__/*.png')"

      - name: Fail if image diffs found
        if: ${{ steps.diff.outputs.files }}
        run: exit 1

      - name: Check CWD
        if: failure()
        run: node -e "console.log('cwd', process.cwd())"

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: image-snapshot-diffs
          path: ${{ github.workspace }}/tests/__image_snapshot_diffs__/*.png

  # Runs snapshot integration tests for MV3
  mv3:
    name: MV3 Integration Tests

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.1.0
        with:
          # Version of PNPM to install
          version: 6.3.0
          # Where to store PNPM files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          # run_install: true

      - name: Check CWD
        run: node -e "console.log('cwd', process.cwd())"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm i

      - name: Run MV3 Vite build tests
        run: pnpm test:ci:mv3:build

      - name: Run MV3 Vite serve tests
        run: pnpm test:ci:mv3:serve

      - name: Check for diff
        id: diff
        run: echo "::set-output name=diff::$(git --no-pager diff --name-only)"

      - name: Fail if diff
        if: ${{ steps.diff.outputs.diff }}
        run: exit 1

      - name: Git diff
        if: failure()
        run: git diff > diff.txt

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mv3-snapshot-diff
          path: diff.txt
          if-no-files-found: ignore
